---
#- hosts: workstation
#  become: true
#  gather_facts: false
#  roles:
#    - osp-facts
- hosts: tag_AnsibleGroup_appdbs, tag_AnsibleGroup_apps, tag_AnsibleGroup_frontends, tag_AnsibleGroup_bastions
#- hosts: tag_instance_filter_three_tier_app_psrivast_redhat_com
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
