- hosts: frontends
  gather_facts: false
  tasks:
  - name: curl website on Prod Env
    uri:
      url: http://localhost
      return_content: yes
    register: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
